/** Every event of the wire by its type, and its schema. */

import { ToolResultSchema } from "./defs.js";
import {
  AttentionAnsweredSchema,
  AttentionRequestedSchema,
  CodeClaimedSchema,
  CodeIssuedSchema,
  ConfirmDeclinedSchema,
  ConfirmGrantedSchema,
  ConfirmRequestSchema,
  CreditsExhaustedSchema,
  CustomSchema,
  DevRequestSchema,
  DocsSourcesSchema,
  DtmfReceivedSchema,
  ErrorEventSchema,
  FleetFullSchema,
  LogCaughtUpSchema,
  LogGapSchema,
  MemoryOpsSchema,
  MessageTakenSchema,
  MessageWaitingSchema,
  PongSchema,
  PromptChangedSchema,
  StateChangedSchema,
  SupervisorEndedSchema,
  SupervisorReleasedSchema,
  SupervisorSaidSchema,
  SupervisorTookOverSchema,
  SupervisorTransferredSchema,
  SupervisorWhisperedSchema,
  ToolCallSchema,
  ToolsChangedSchema,
  UserStateChangedSchema,
  UserTranscriptSchema,
  UserTurnEndedSchema,
} from "./events.js";
import {
  AgentConfiguredSchema,
  AgentDetachedSchema,
  AgentDrainingSchema,
  AgentRegisteredSchema,
  AgentStateChangedSchema,
  AgentTranscriptSchema,
  AgentTurnEndedSchema,
  CallAttachedSchema,
  CallbackRequestedSchema,
  CallClaimedSchema,
  CallDialingSchema,
  CallEndedSchema,
  CallLineSchema,
  CallRingingSchema,
  CallScoreSchema,
  CallStartedSchema,
  CallSummarySchema,
  CallTransferredSchema,
} from "./events-call.js";
import {
  AvatarMetricsSchema,
  EOTInferenceMetricsSchema,
  EOUMetricsSchema,
  InterruptionMetricsSchema,
  LLMMetricsSchema,
  RealtimeModelMetricsSchema,
  STTMetricsSchema,
  TTSMetricsSchema,
  VADMetricsSchema,
} from "./metrics.js";
import {
  EventReceivedSchema,
  ParticipantJoinedSchema,
  ParticipantLeftSchema,
  ParticipantSpeakingSchema,
  RoomOpenedSchema,
  RoomSentSchema,
  TrackPublishedSchema,
  TrackUnpublishedSchema,
} from "./room.js";

/** Every event by its wire type; the codec looks the schema up here. */
export const EVENT_SCHEMAS = {
  "agent.configured": AgentConfiguredSchema,
  "agent.detached": AgentDetachedSchema,
  "agent.draining": AgentDrainingSchema,
  "agent.registered": AgentRegisteredSchema,
  "agent.state": AgentStateChangedSchema,
  "agent.transcript": AgentTranscriptSchema,
  "attention.answered": AttentionAnsweredSchema,
  "attention.requested": AttentionRequestedSchema,
  "call.attached": CallAttachedSchema,
  "call.claimed": CallClaimedSchema,
  "call.dialing": CallDialingSchema,
  "call.ended": CallEndedSchema,
  "call.line": CallLineSchema,
  "call.ringing": CallRingingSchema,
  "call.score": CallScoreSchema,
  "call.started": CallStartedSchema,
  "call.summary": CallSummarySchema,
  "call.transferred": CallTransferredSchema,
  "callback.requested": CallbackRequestedSchema,
  "code.claimed": CodeClaimedSchema,
  "code.issued": CodeIssuedSchema,
  "confirm.declined": ConfirmDeclinedSchema,
  "confirm.granted": ConfirmGrantedSchema,
  "confirm.request": ConfirmRequestSchema,
  "credits.exhausted": CreditsExhaustedSchema,
  "custom": CustomSchema,
  "dev.request": DevRequestSchema,
  "docs.sources": DocsSourcesSchema,
  "dtmf.received": DtmfReceivedSchema,
  "error": ErrorEventSchema,
  "event.received": EventReceivedSchema,
  "fleet.full": FleetFullSchema,
  "log.caught_up": LogCaughtUpSchema,
  "log.gap": LogGapSchema,
  "memory.ops": MemoryOpsSchema,
  "message.taken": MessageTakenSchema,
  "message.waiting": MessageWaitingSchema,
  "metrics.avatar": AvatarMetricsSchema,
  "metrics.eot": EOTInferenceMetricsSchema,
  "metrics.eou": EOUMetricsSchema,
  "metrics.interruption": InterruptionMetricsSchema,
  "metrics.llm": LLMMetricsSchema,
  "metrics.realtime": RealtimeModelMetricsSchema,
  "metrics.stt": STTMetricsSchema,
  "metrics.tts": TTSMetricsSchema,
  "metrics.vad": VADMetricsSchema,
  "participant.joined": ParticipantJoinedSchema,
  "participant.left": ParticipantLeftSchema,
  "participant.speaking": ParticipantSpeakingSchema,
  "pong": PongSchema,
  "prompt.changed": PromptChangedSchema,
  "room.opened": RoomOpenedSchema,
  "room.sent": RoomSentSchema,
  "state.changed": StateChangedSchema,
  "supervisor.ended": SupervisorEndedSchema,
  "supervisor.released": SupervisorReleasedSchema,
  "supervisor.said": SupervisorSaidSchema,
  "supervisor.took_over": SupervisorTookOverSchema,
  "supervisor.transferred": SupervisorTransferredSchema,
  "supervisor.whispered": SupervisorWhisperedSchema,
  "tool.call": ToolCallSchema,
  "tool.result": ToolResultSchema,
  "tools.changed": ToolsChangedSchema,
  "track.published": TrackPublishedSchema,
  "track.unpublished": TrackUnpublishedSchema,
  "turn.agent": AgentTurnEndedSchema,
  "turn.user": UserTurnEndedSchema,
  "user.state": UserStateChangedSchema,
  "user.transcript": UserTranscriptSchema,
} as const;
export type EventType = keyof typeof EVENT_SCHEMAS;

/** The one event that ends a call: after it nothing more is true and the log is sealed. */
export const TERMINAL_EVENT: EventType = "call.score";

